% -------------------------------------------------------------------
%  Generated by MATLAB on 6-Mar-2025 11:24:55
%  MATLAB version: 9.10.0.1602886 (R2021a)
% -------------------------------------------------------------------
saveVarsMat = load('sinais.mat');

x1 = saveVarsMat.x1; % <279634x1 double> sinal discreto obtido pela amostragem a uma taxa de T1 = (1/8000)

x2 = saveVarsMat.x2; % <3355608x1 double> sinal discreto obtido pela amostragem a uma taxa de T2 = (1/96000)

clear saveVarsMat;
